# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://osl-incubator.github.io/osl-hugo.github.io/"  # Include trailing slash
#title = "OpenScienceLabs"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
#copyright = "Â© Content"
# canonifyurls = true
# paginate = 10
# theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "es"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
