[[main]]
  name = "Home"
  url = ""
  weight = -110

#[[main]]
#  name = "Actividades"
#  url = "post/archive/"
#  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Acerca de"
  identifier = "about"
  weight = 122
[[main]]
  parent = "about"
  name = "Gu√≠as"
  url = "guidelines/"
[[main]]
  parent = "about"
  name = "Equipo"
  url = "team/"
[[main]]
  parent = "about"
  name = "Asociados"
  url = "partners/"


#[[main]]
#  name = "About"
#  url = "about/"
#  weight = 121

# social menu links
[[social]]
  name = "youtube"
  type = "social"
  url = "https://www.youtube.com/@opensciencelabs"
  weight = 1
[[social]]
  name = "github"
  type = "social"
  weight = 2
  url = "https://github.com/OpenScienceLabs"
[[social]]
  name = "twitter"
  weight = 3
  url = "https://twitter.com/opensciencelabs"
[[social]]
  name = "linkedin"
  weight = 2
  url = "https://www.linkedin.com/company/open-science-labs/"
[[social]]
  name = "facebook"
  type = "social"
  url = "https://www.facebook.com/opensciencelabscommunity"
  weight = 4
[[social]]
  name = "discord"
  type = "social"
  url = "https://opensciencelabs.org/discord"
  weight = 5
[[social]]
  name = "rss"
  weight = 6
  url = "index.xml"



# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://www.facebook.com/opensciencelabscommunity"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "http://discord.opensciencelabs.org/"